name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn compile

      - name: Run Tests
        run: mvn test

      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      - name: Upload JaCoCo Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Run Gitleaks for secrets detection
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml  # facultatif
          fail: true

      - name: Dependency Vulnerability Check (OWASP)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'cyberdemo'
          format: 'HTML'
          out: 'reports'
          scan: '.'

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: reports/
